const foods = [
  {
    id: 4,
    img: "food_4.png",
    name: "Yin & Yang",
    price: 15500,
    status: "Pending",
    quantity: 1,
    total: 4000,
  },
  {
    id: 5,
    img: "food_5.png",
    name: "Pancakes",
    price: 2000,
    status: "Pending",
    quantity: 1,
    total: 2000,
  },
  {
    id: 6,
    img: "food_6.png",
    name: "Huevos Rancheros",
    price: 14000,
    status: "Pending",
    quantity: 1,
    total: 14000,
  },

  {
    id: 9,
    img: "food_11.png",
    name: "Chinese Special Rice with Beef Sauce",
    price: 16800,
    status: "Pending",
    quantity: 1,
    total: 16800,
  },
  {
    id: 11,
    img: "food_13.png",
    name: "Coconut Rice with Stewed Beef",
    price: 14800,
    status: "Pending",
    quantity: 1,
    total: 14800,
  },
  {
    id: 12,
    img: "food_14.png",
    name: "Asun Pepper Jollof Rice",
    price: 10000,
    status: "Pending",
    quantity: 1,
    total: 10000,
  },
  {
    id: 13,
    img: "food_15.png",
    name: "Obosi Sauce with Shrimp Rice",
    price: 20800,
    status: "Pending",
    quantity: 1,
    total: 20800,
  },
  {
    id: 14,
    img: "food_16.png",
    name: "Lotus Pancakee",
    price: 12500,
    status: "Pending",
    quantity: 1,
    total: 12500,
  },
  
];

export default foods;
